### ISSUE TITLE
您好，这个有数据库文件吗？

### ISSUE THREAD

**Issue by caixinyuan** [liulixing520/sude#3]

**Comment by liulixing520** [comment]
没有，启动项目即可以自动创建数据库
&nbsp;


该邮件从移动设备发送




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 晚上9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [liulixing520/sude] 您好，这个有数据库文件吗？ (#3)





 
Closed #3 as completed.
